export const SET_STUDENTS = 'SET_STUDENTS'

export const SET_SIGNING_IN = 'SET_SIGNING_IN'
export const SET_USER_TOKEN = 'SET_USER_TOKEN'
export const SET_ONLINE = 'SET_ONLINE'
export const ADD_CONSISTENCY = 'ADD_CONSISTENCY'
export const CLEAR_CONSISTENCY = 'CLEAR_CONSISTENCY'
